### ISSUE TITLE
Hello looking for a front-end react dev to help me build a learning (practice) project i am a backend dev  

### ISSUE THREAD

**Issue by GSGSDgggdzez** [Mel-Turham/Meyazone#3]
Hi there,

I hope this message finds you well. I'm currently working on a learning project to build a streaming app, and I'm looking for a frontend developer who is interested in collaborating with me from start to end. I'm a backend developer with experience in several programming languages and frameworks, but I have limited experience in frontend development.

The streaming app I'm working on will allow users to watch their favorite shows and movies on demand. I don't have a specific vision for the application's functionality and user experience yet, and I believe that working with a skilled frontend developer like you would be a great opportunity for us to build something amazing together.

Here are a few reasons why I think this could be a valuable opportunity for both of us:

1. Shared vision and collaboration: By working together from start to end, we can share our ideas and vision for the project, and collaborate on building a high-quality streaming app that we can both be proud of.
2. Shared vision and collaboration: By working together from start to end, we can share our ideas and vision for the project, and collaborate on building a high-quality streaming app that we can both be proud of.
3. Flexible schedule: I understand that you might have other commitments, so we can work around your schedule. We can communicate and collaborate using tools that are convenient for you.
4. Portfolio and recognition: By working together on a project that we can both showcase in our portfolios, we can build our reputation and recognition in the industry.
 If you're interested in learning more about the project or discussing a potential collaboration, please let me know. I'm looking forward to hearing from you!

Best regards,
Defree harold 
Email
defreeharold@duck.com

**Comment by Mel-Turham** [comment]
Hi Defree,

Thank you for reaching out! I appreciate your kind words and the opportunity to collaborate on your streaming app project. It sounds like an exciting venture, and I’d love to learn more about it.

As a frontend developer, I believe my skills can complement your backend expertise, especially in creating a user-friendly experience for the app. I’m also interested in discussing the project’s scope, potential features, and how we can effectively collaborate to bring your vision to life.

Could we schedule a time to chat further about this? I’m flexible with timings, so please let me know what works for you.

Looking forward to hearing from you!

Best regards,

**Comment by GSGSDgggdzez** [comment]
hello brother these project is learning base and there is no renumeration and in the front end we are using next js

**Comment by Mel-Turham** [comment]
So you want me to work for free then?
No motivation, just writing code to learn?

By the way, which country are you in?
